---
- hosts: nios
  connection: local
  tasks:
    - name: return the next available IP addresses for network 10.10.2.0/24
      set_fact:
        ipaddr: "{{ lookup('nios_next_ip', '10.20.0.0/25', provider=nios_provider) }}"
        provider: "{{nios_provider}}"
    - name: Print the range of IPs calculated above
      debug:
        var: ipaddr
    - name: configure a host
      nios_host_record:
        name: v60.lab.local
        ipv4addrs:
            - ipv4addr: "{{ item }}"
        comment: this is a test comment
        extattrs:
          Site="Test"
          Testing="Sif"
        state: present
        provider: "{{nios_provider}}"
      loop: "{{ ipaddr }}"